/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: C. Anastasiadis (https://sketchfab.com/bagatir)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/latern-5936e9dae501471facc19b183a6241e3
Title: Latern
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube009_0: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
}

export function Lantern(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('https://netgfx.com/trunk/threedmodels/latern.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_0.geometry}
          material={materials.Material}
          position={[6.878, 0.883, 4.043]}
          scale={[0.065, 0.318, 0.056]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('https://netgfx.com/trunk/threedmodels/latern.glb')
